### ISSUE TITLE
version 2.0 roadmap

### ISSUE THREAD

**Issue by azadkuh** [azadkuh/cmus-osx#8]
this is an open discussion about the future release of `cmus-osx` due to new design mostly done by @PhilipTrauner.

there are some missing features or issues in current master branch in comparison to the older releases (i.e. v1.2):

- the filename `/tmp/notify.log` is so global: use a more specific file name (to help name clashing with other logs)

- the notification badge on Notification center does not show the cover / album art:
<img width="692" alt="screen shot 1395-10-19 at 18 28 06" src="https://cloud.githubusercontent.com/assets/6501462/21750776/5266eabe-d5d0-11e6-814c-649d507175c8.png">

- the current status of cmus (playing, paused, ...) is missed. imho it's nice to include them

- automatic installation of `cmus-osx/notify.py` in `~/.config/cmus/autosave` by `setup.py`

- when streaming from internet, no notification is created.

- we are programmer, we may need a graphic designer to make a good looking logo/icon! ;-)

**Comment by PhilipTrauner** [comment]
* Status  
    I initially removed the status to be more in line with the iTunes notification style, I suggest a new config entry for that.

* Notification badge does not contain album
    iTunes notifications don't display them either. Config option is the best way to go, I think.

* Internet streaming  
    I probably broke this while refactoring, will setup a test environment for internet streams.

* Autosave edit
    After getting into the cmus plugin ecosystem I noticed that many heavy users actually create a shell script for their status_display_program in which they call multiple programs. Instead of writing directly to status_display_program I'd prefer to create such a shell script.

* Icon  
    Definitely!

* Traceback file-name
    Should be an option in the config. I might switch the config management over to [Meh](https://github.com/PhilipTrauner/Meh) (shameless advertising) if more config entries pop up.

Some more suggestion:
The hardware buttons of Earpods (or any other headphones for that matter) don't work. I already tried hacking together a solution in Python with MediaPlayer, but could not get the callback functionality to accept a python function wrapped in a selector. 
If I don't find a solution I might have to rewrite cmus-osx in Swift or ObjC. I really don't want to essentially start from scratch again, so this is more of a last resort thing.

Locking for media-key.py should also be implemented. If cmus is relaunched very quickly it might produce two or more instances which really messes up the controls.

Better inline documentation. Documentation generator is overkill, still there is some pyobjc stuff in notify.py that took me ages to find.

If a new logo is found I suggest a rewrite of the README to be extra fancy.

**Comment by PhilipTrauner** [comment]
Sorry for the silence, I will dedicate my weekend to:

- [x] Move the config "engine" over to Meh
- [x] Config entry for display mode
- [x] Config entry for app icon
- [x] Config entry for notification on pause
- [x] Config entry for iTunes style notifications
- [x] Different log name
- [x] Make readme prettier

**Comment by PhilipTrauner** [comment]
It's been a while but I think the v2.0.0 milestone is finally reached. Streaming notification work again and iTunes doesn't pop-up anymore when media keys are pressed.

I don't want to sound egotistical but would you mind transferring the repository ownership to me?

**Comment by azadkuh** [comment]
dear @PhilipTrauner 
you already have full control on this repo and most of its credit goes to you.

> would you mind transferring the repository ownership to me?

sure!

**Comment by PhilipTrauner** [comment]
@azadkuh Thank you so much! Your project is in good hands 😎

**Comment by rtaibah** [comment]
Love this project. Any updates on notifications when streaming?

**Comment by PhilipTrauner** [comment]
@rtaibah Just tried out [a random stream](http://stream.fragradio.co.uk:8000/autodj.m3u) and everything seemed to work. Would you mind posting the url of the stream you are having trouble with?
